service: fyp-github-bot 

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1

functions:
  main:
    handler: webhook.main
    events:
    - http:
        path: /webhook
        method: post
  createRepo:
    handler: main.createRepo
    events:
    - http:
        path: /create-repo
        method: post
        cors: true