version: 2.4
jobs:
  build:
    docker:
      - image: circleci/node:8.10

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - dependencies-cache-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-cache

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            npm install
            
      # echo `echo $PRIVATEKEY | base64 --decode` >> private.pem
      - run:
          name: Inject Private Key
          command: |
            echo $PRIVATEKEY | base64 --decode | >> private.pem
            cat private.pem

      - run:
          name: Deploy application
          command: sls deploy

      - save_cache:
          paths:
            - node_modules
          key: dependencies-cache-{{ checksum "package.json" }}
